baseURL = '/'
languageCode = 'en-us'
title = 'ReacSoft - AI Enterprise Solutions'
description = 'Cutting-edge AI engineering and enterprise end-to-end system development'
theme = 'long-teng'

[params]
    Author = 'ReacSoft'
